language: node_js
node_js:
  - "8.10"

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher -c hiptest-publisher.conf --only=tests --test-run-id=135450

script:
  - ./node_modules/jasmine-xml-reporter/bin/jasmine.js --junitreport

after_script:
  - hiptest-publisher -c hiptest-publisher.conf --push="results.xml" --test-run-id=135450